# SPDX-FileCopyrightText: 2025 Chen Linxuan <me@black-desk.cn>
#
# SPDX-License-Identifier: MIT

name: Continuous Deployment

on:
  push:
    tags:
      - v*-*
    branches:
      - master

jobs:
  # This is a neovim configuration project and doesn't need goreleaser
  # goreleaser:
  #   permissions:
  #     contents: write
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: black-desk/workflows/goreleaser@master

  # Simple job for neovim configuration deployment
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Neovim configuration deployed!"
